main: de.murmelmeister.essentials.MurmelEssentials
name: MurmelEssentials
version: ${project.version}
api-version: 1.20
author: Murmelmeister
description: MurmelEssentials is a plugin that adds a lot of useful commands to your server.
website: https://www.youtube.com/Murmelmeister